### ISSUE TITLE
The extension has some issues with the latest Quart

### ISSUE THREAD

**Issue by filak** [joeblackwaslike/quart-sqlalchemy#9]
I have been trying to use SQLAlchemy using your extension (pypi version 2.0.0 and the lastest 3.0.2) with the lastest Quart following the example from https://pypi.org/project/quart-sqlalchemy/ but without success.

I have created a testing repo: https://github.com/filak/Quart-db-test

So far it seems to me that the db is not being properly initialized...

I see that after calling

     db = SQLAlchemy(app)

the engine/s both contain traceback error - ... RuntimeError('Not within an app context')

Currently I am stuck, any advice would be highly appreciated.

**Comment by KevinRiggen** [comment]
From what I can tell, this package is not up to date with the latest Quart and is raising import errors since this Quart commit: https://github.com/pallets/quart/commit/c9b555ff284bb54a45adab44c8e6d78ab8713da0

**Comment by filak** [comment]
Yes, but this is just a partial issue. When reverting to the version before Blinker update - ie. https://github.com/pallets/quart/commit/c9768af63097c6ef3405cfd42d46b49ad6d1436d

you get again the original error:

     with app.app_context():
         AttributeError: __enter__

So far I have not been able to find a working combination of versions of Quart + quart-sqlalchemy

**Comment by KevinRiggen** [comment]
Same.On Jul 26, 2023, at 11:07 PM, filak ***@***.***> wrote:﻿
Yes, but this is just a partial issue. When reverting to the version before Blinker update - ie. ***@***.***
you get again the original error:
 with app.app_context():
     AttributeError: __enter__

So far I have not been able to find a working combination of versions of Quart + quart-sqlalchemy

**Comment by joeblackwaslike** [comment]
@filak  @KevinRiggen  Hey all, I haven't had tons of free time recently to contribute to this but hope to with the upcoming holiday break.

I see we have some compatibility problems with the latest quart, I hear you.  Let me push a fix for that, its probably very minor.

**Comment by joeblackwaslike** [comment]
@filak @KevinRiggen 3.0.4 should fix things
